trigger:
- master

resources:
- repo: self

stages:
- stage: Scale
  displayName: Deploy image
  jobs:
    - job:
      displayName: Scale deployment
      steps:
      - task: KubernetesManifest@0
        displayName: Scale
        inputs: 
          action: scale
          kind: deployment
          name: service-deployment
          replicas: $(replicas)
          kubernetesServiceConnection: 'k8s-service-connection'
          namespace: default