trigger:
- master

resources:
- repo: self

stages:
- stage: CI
  displayName: Create artifacts
  jobs:  
  - job: Deploy
    displayName: Download artifacts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'helloartifact'
        publishLocation: 'Container'
    #- task: KubernetesManifest@0
    
    #  inputs:
    #    action: 'deploy'
    #    kubernetesServiceConnection: 'k8s-service-connection'
    #    namespace: 'default'
    #    manifests: '$(System.ArtifactsDirectory)/configuration/k8s/deployment.yaml'
    #    containers: 'kubectlcz/hello_rest_api:$(tag)'
- stage: CD
  displayName: CD Stage
  dependsOn: CI
  jobs:
    - deployment: 
      displayName: deploy
      environment: Testing.testing
      strategy:
         runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    artifactName: 'helloartifact'
                    itemPattern: '**/*.yaml'
                    targetPath: '$(System.ArtifactsDirectory)'
                - task: KubernetesManifest@0
                  inputs:
                    action: 'deploy'
                    manifests: '$(System.ArtifactsDirectory)/configuration/k8s/deployment.yaml'
                    containers: 'kubectlcz/hello_rest_api:$(tag)' 